### ISSUE TITLE
Support for Symfony 6.1

### ISSUE THREAD

**Issue by RodzynDev** [artgris/FileManagerBundle#110]
Hello!

Today, during upgrading my Symfony project from 5.3 to 6.1 I got an issue with this package:

```Run composer recipes at any time to see the status of your Symfony recipes.
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Config\Definition\Builder\NodeBuilder::textNode() in /home/rodzyn/Projects/*****/vendor/artgris/filemanager-bundle/DependencyInjection/Configuration.php:37
!!  Stack trace:
!!  #0 /home/rodzyn/Projects/*****/vendor/symfony/config/Definition/Processor.php(46): Artgris\Bundle\FileManagerBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
!!  #1 /home/rodzyn/Projects/*****/vendor/symfony/dependency-injection/Extension/Extension.php(109): Symfony\Component\Config\Definition\Processor->processConfiguration()
!!  #2 /home/rodzyn/Projects/*****/vendor/artgris/filemanager-bundle/DependencyInjection/ArtgrisFileManagerExtension.php(22): Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration()
!!  #3 /home/rodzyn/Projects/*****/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Artgris\Bundle\FileManagerBundle\DependencyInjection\ArtgrisFileManagerExtension->load()
!!  #4 /home/rodzyn/Projects/*****/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(42): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process()
!!  #5 /home/rodzyn/Projects/*****/vendor/symfony/dependency-injection/Compiler/Compiler.php(73): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process()
!!  #6 /home/rodzyn/Projects/*****/vendor/symfony/dependency-injection/ContainerBuilder.php(716): Symfony\Component\DependencyInjection\Compiler\Compiler->compile()
!!  #7 /home/rodzyn/Projects/*****/vendor/symfony/http-kernel/Kernel.php(538): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
!!  #8 /home/rodzyn/Projects/*****/vendor/symfony/http-kernel/Kernel.php(767): Symfony\Component\HttpKernel\Kernel->initializeContainer()
!!  #9 /home/rodzyn/Projects/*****/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
!!  #10 /home/rodzyn/Projects/*****/vendor/symfony/framework-bundle/Console/Application.php(166): Symfony\Component\HttpKernel\Kernel->boot()
!!  #11 /home/rodzyn/Projects/*****/vendor/symfony/framework-bundle/Console/Application.php(72): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #12 /home/rodzyn/Projects/*****/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
!!  #13 /home/rodzyn/Projects/*****/bin/console(42): Symfony\Component\Console\Application->run()
!!  #14 {main}
!!    thrown in /home/rodzyn/Projects/*****/vendor/artgris/filemanager-bundle/DependencyInjection/Configuration.php on line 37
!!
Script @auto-scripts was called via post-install-cmd
```
Could you do some upgrades to your package to be compatible with the latest Symfony version (means 6.1)?
Thank you!

**Comment by RodzynDev** [comment]
Nevermind, I needed to update package version to the lastest ;) Closing issue ;)
